package com.example.onboarding.dao;

import com.example.onboarding.model.Customer;
import com.example.onboarding.util.ConnectionManager;
import com.example.onboarding.util.DatabaseConfig;

import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

public class CustomerDao {
    private final DatabaseConfig databaseConfig;

    public CustomerDao(DatabaseConfig databaseConfig) {
        this.databaseConfig = databaseConfig;
    }

    public void initializeSchema() throws SQLException {
        String ddl = "BEGIN "
                + "EXECUTE IMMEDIATE 'CREATE TABLE CUSTOMER_ONBOARDING ("
                + "ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                + "CUSTOMER_NAME VARCHAR2(150) NOT NULL, "
                + "COMPANY_NAME VARCHAR2(150) NOT NULL, "
                + "EMAIL VARCHAR2(150) NOT NULL, "
                + "PHONE_NUMBER VARCHAR2(30), "
                + "ADDRESS_LINE1 VARCHAR2(200), "
                + "ADDRESS_LINE2 VARCHAR2(200), "
                + "CITY VARCHAR2(80), "
                + "STATE VARCHAR2(80), "
                + "POSTAL_CODE VARCHAR2(20), "
                + "COUNTRY VARCHAR2(80), "
                + "ONBOARDING_STATUS VARCHAR2(40) NOT NULL, "
                + "NOTES VARCHAR2(500), "
                + "CREATED_DATE DATE DEFAULT SYSDATE NOT NULL"
                + ")'; "
                + "EXCEPTION WHEN OTHERS THEN "
                + "IF SQLCODE != -955 THEN RAISE; END IF; "
                + "END;";

        try (Connection connection = ConnectionManager.getConnection(databaseConfig);
             PreparedStatement statement = connection.prepareStatement(ddl)) {
            statement.execute();
        }
    }

    public void save(Customer customer) throws SQLException {
        String sql = "INSERT INTO CUSTOMER_ONBOARDING ("
                + "CUSTOMER_NAME, COMPANY_NAME, EMAIL, PHONE_NUMBER, ADDRESS_LINE1, ADDRESS_LINE2, "
                + "CITY, STATE, POSTAL_CODE, COUNTRY, ONBOARDING_STATUS, NOTES, CREATED_DATE"
                + ") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

        try (Connection connection = ConnectionManager.getConnection(databaseConfig);
             PreparedStatement statement = connection.prepareStatement(sql)) {
            statement.setString(1, customer.getCustomerName());
            statement.setString(2, customer.getCompanyName());
            statement.setString(3, customer.getEmail());
            statement.setString(4, customer.getPhoneNumber());
            statement.setString(5, customer.getAddressLine1());
            statement.setString(6, customer.getAddressLine2());
            statement.setString(7, customer.getCity());
            statement.setString(8, customer.getState());
            statement.setString(9, customer.getPostalCode());
            statement.setString(10, customer.getCountry());
            statement.setString(11, customer.getOnboardingStatus());
            statement.setString(12, customer.getNotes());
            statement.setDate(13, Date.valueOf(customer.getCreatedDate()));
            statement.executeUpdate();
        }
    }

    public List<Customer> findAll() throws SQLException {
        String sql = "SELECT ID, CUSTOMER_NAME, COMPANY_NAME, EMAIL, PHONE_NUMBER, ADDRESS_LINE1, ADDRESS_LINE2, "
                + "CITY, STATE, POSTAL_CODE, COUNTRY, ONBOARDING_STATUS, NOTES, CREATED_DATE "
                + "FROM CUSTOMER_ONBOARDING ORDER BY CREATED_DATE DESC, ID DESC";

        List<Customer> customers = new ArrayList<>();
        try (Connection connection = ConnectionManager.getConnection(databaseConfig);
             PreparedStatement statement = connection.prepareStatement(sql);
             ResultSet resultSet = statement.executeQuery()) {
            while (resultSet.next()) {
                Customer customer = new Customer();
                customer.setId(resultSet.getLong("ID"));
                customer.setCustomerName(resultSet.getString("CUSTOMER_NAME"));
                customer.setCompanyName(resultSet.getString("COMPANY_NAME"));
                customer.setEmail(resultSet.getString("EMAIL"));
                customer.setPhoneNumber(resultSet.getString("PHONE_NUMBER"));
                customer.setAddressLine1(resultSet.getString("ADDRESS_LINE1"));
                customer.setAddressLine2(resultSet.getString("ADDRESS_LINE2"));
                customer.setCity(resultSet.getString("CITY"));
                customer.setState(resultSet.getString("STATE"));
                customer.setPostalCode(resultSet.getString("POSTAL_CODE"));
                customer.setCountry(resultSet.getString("COUNTRY"));
                customer.setOnboardingStatus(resultSet.getString("ONBOARDING_STATUS"));
                customer.setNotes(resultSet.getString("NOTES"));
                Date createdDate = resultSet.getDate("CREATED_DATE");
                customer.setCreatedDate(createdDate == null ? LocalDate.now() : createdDate.toLocalDate());
                customers.add(customer);
            }
        }

        return customers;
    }
}
